// <auto-generated />
using System;
using Cars_Bikes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cars_Bikes.Migrations.FourWheelerBrandDBMigrations
{
    [DbContext(typeof(FourWheelerDB))]
    [Migration("20240708034205_addFWUpcomingAndLatestNews")]
    partial class addFWUpcomingAndLatestNews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cars_Bikes.Models.FWLatestNews", b =>
                {
                    b.Property<int>("FWLatestNewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FWLatestNewsId"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsDetail")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("NewsHeading")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewsSummary")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("FWLatestNewsId");

                    b.ToTable("FWLatestNews");
                });

            modelBuilder.Entity("Cars_Bikes.Models.FourWheelerBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FourWheelerBrandName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FourWheelerBrands");
                });

            modelBuilder.Entity("Cars_Bikes.Models.UpcomingCar", b =>
                {
                    b.Property<int>("UpcomingCarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpcomingCarId"));

                    b.Property<DateTime?>("ExpectedLaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpcomingCarDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpcomingCarName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UpcomingCarId");

                    b.ToTable("UpcomingCars");
                });
#pragma warning restore 612, 618
        }
    }
}
